import { Topping } from '../model/topping.model';

export const toppings: Topping[] = [
  {
    name: 'Salami',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Meat',
  },
  {
    name: 'Salami Piccante',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Meat',
  },
  {
    name: 'Proscuitto Cotto',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Meat',
  },
  {
    name: 'Scharfe Salami',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Meat',
  },
  {
    name: 'Edammer',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Cheese',
  },
  {
    name: 'Parmesan Flakes',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 1,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Pinsa'],
    toppingCategory: 'Cheese',
    availableAsExtra: true,
  },
  {
    name: 'Veganer Käse',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Cheese',
  },
  {
    name: 'Parmesan',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Pinsa', 'Bowl'],
    toppingCategory: 'Cheese',
  },
  {
    name: 'Croutons',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Bowl'],
    toppingCategory: 'Other',
  },
  {
    name: 'Limetten',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Bowl'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Falafel',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Bowl'],
    toppingCategory: 'Other',
  },
  {
    name: 'Hummus',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Bowl'],
    toppingCategory: 'Other',
  },
  {
    name: 'Blumenkohl',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Bowl'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Sonnenblumenkerne',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Bowl'],
    toppingCategory: 'Other',
  },
  {
    name: 'Walnüsse',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Bowl'],
    toppingCategory: 'Other',
  },
  {
    name: 'Tofu',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Bowl'],
    toppingCategory: 'Other',
  },

  {
    name: 'Gouda',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Cheese',
  },
  {
    name: 'Käsemix',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Cheese',
  },
  {
    name: 'Rucola',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 1,
    image: 'assets/images/toppings/rucola.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Vegetable',
    availableAsExtra: true,
  },
  {
    name: 'Rucola',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 1,
    image: 'assets/images/toppings/rucola.png',
    category: ['Bowl'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'gehackter Knoblauch',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 0.7,
    image: 'assets/images/toppings/garlic.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Vegetable',
    availableAsExtra: true,
  },
  {
    name: 'Kapern',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Tomaten',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Oliven',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Schinken',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Meat',
  },
  {
    name: 'Thunfisch',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Fish',
  },
  {
    name: 'Ananas',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Fruit',
  },
  {
    name: 'Spinat',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Basilikum',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 1,
    image: 'assets/images/toppings/basilikum.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Vegetable',
    availableAsExtra: true,
  },
  {
    name: 'Pilze',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'braune Champignons',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Mais',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Scharfe Peperoni',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Rote Chili',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Paprikastreifen',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Datteltomaten',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Zwiebeln',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Tomatensauce',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Sauce',
  },
  {
    name: 'Trüffelöl',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 1.5,
    image: 'assets/images/toppings/truffel-oil.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Sauce',
    availableAsExtra: true,
  },
  {
    name: 'Pizzasauce',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan'],
    toppingCategory: 'Sauce',
  },
  {
    name: 'Hot Chili Sauce',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 1,
    image: 'assets/images/toppings/hot-sauce.png',
    category: ['Pizza', 'Pinsa'],
    toppingCategory: 'Sauce',
    availableAsExtra: true,
  },
  {
    name: 'Knoblauch-sauce',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 1,
    image: 'assets/images/toppings/garlic-sauce.png',
    category: ['Pizza', 'Pinsa'],
    toppingCategory: 'Sauce',
    availableAsExtra: true,
  },
  {
    name: 'Vegane Pestosauce',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 1,
    image: 'assets/images/toppings/pesto.png',
    category: ['Pizza', 'Pinsa', 'Vegan'],
    toppingCategory: 'Sauce',
    availableAsExtra: true,
  },
  {
    name: 'Vegane Knoblauchsauce',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 1,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Vegan'],
    toppingCategory: 'Sauce',
  },
  {
    name: 'Pinsasauce',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pinsa', 'Vegan'],
    toppingCategory: 'Sauce',
  },
  {
    name: 'BBQ-Sauce',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Sauce',
  },
  {
    name: 'Olivenöl',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 1,
    image: 'assets/images/toppings/olive-oil.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Sauce',
    availableAsExtra: true,
  },
  {
    name: 'Hollondaise-Sauce',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Pizza', 'Vegan', 'Pinsa'],
    toppingCategory: 'Sauce',
  },

  {
    name: 'Oliven',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/menu/items/pizza-salami.png',
    category: ['Bowl'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Tomaten',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Edamame',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Soja-Sprossen',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Avocado',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Zwiebeln (rot)',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Garnelen',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Fish',
  },
  {
    name: 'Hühnchen',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Meat',
  },
  {
    name: 'Mango',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Fruit',
  },
  {
    name: 'Süßkartoffeln',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Kichererbsen',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Cashewnüsse',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Other',
  },
  {
    name: 'Mango Chutney',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Sauce',
  },

  {
    name: 'Lauchzwiebeln',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Karotten',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Basilikum',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Other',
  },
  {
    name: 'Reis (Basmati)',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Rindfleisch (mariniert)',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Meat',
  },
  {
    name: 'Gurken',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Mais',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Paprika',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Vegetable',
  },
  {
    name: 'Thunfisch',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Fish',
  },
  {
    name: 'Schinken',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Meat',
  },
  {
    name: 'Ei',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Other',
  },
  {
    name: 'Feta',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: ['Bowl'],
    toppingCategory: 'Cheese',
  },
];
