import { Topping } from '../../shared/model/topping.model';
import { Bowl, FoodCategory, Pizza } from '../../shared/model/food.model';

export const foodCategories: FoodCategory[] = ['Pizza', 'Bowl'];

export const pizzas: Array<Pizza> = [
  {
    name: 'Margherita',
    category: 'Pizza',
    description:
      'Die klassische Margherita-Pizza ist ein kulinarisches Meisterwerk aus dünnem Teig, reifen Tomaten, cremigem Mozzarella und frischem Basilikum – einfach köstlich!',
    price: 12,
    image: 'assets/images/menu/items/Pizza-margherita.png',
    contains: {
      vegan: true,
      gluten: true,
      heat: true,
      cheese: true,
    },
    tags: {},
    order: 1,
    toppings: [],
  },
  {
    name: 'Salami',
    category: 'Pizza',
    description:
      'Die herzhafte Pizza Salami verwöhnt den Gaumen mit großzügig belegter knuspriger Kruste, deftiger Salami und schmelzendem Mozzarella - ein wahrer Genuss für Salami-Liebhaber!',
    price: 14.9,
    image: 'assets/images/menu/items/Pizza-salami.png',
    contains: {
      gluten: true,
      beef: true,
      heat: true,
      cheese: true,
    },
    tags: {
      recommendation: true,
    },
    order: 2,
    toppings: [],
  },
  {
    name: 'Diavolo',
    category: 'Pizza',
    description:
      'Die pikante Pizza Diavolo ist ein scharfer Genuss mit würziger Salami, feuriger Peperoni und einer perfekten Mischung aus Aromen.',
    price: 14.9,
    image: 'assets/images/menu/items/Pizza-diavolo.png',
    contains: {
      gluten: true,
      beef: true,
      heat: true,
      hot: true,
      cheese: true,
    },
    tags: {},
    order: 3,
    toppings: [],
  },
  {
    name: 'Diavolo Picante',
    category: 'Pizza',
    description:
      'Die pikante Pizza Diavolo ist ein scharfer Genuss mit würziger Salami, feuriger Peperoni und einer perfekten Mischung aus Aromen.',
    price: 14.9,
    image: 'assets/images/menu/items/Pizza-diavolo-picante.png',
    contains: {
      gluten: true,
      beef: true,
      heat: true,
      hot: true,
      cheese: true,
    },
    tags: {},
    order: 4,
    toppings: [],
  },
  {
    name: 'Italian Delight',
    category: 'Pizza',
    description:
      'Die herzhafte Pizza Salami verwöhnt den Gaumen mit großzügig belegter knuspriger Kruste, deftiger Salami und schmelzendem Mozzarella - ein wahrer Genuss für Salami-Liebhaber!',
    price: 14.9,
    image: 'assets/images/menu/items/Pizza-italian-delight.png',
    contains: {
      gluten: true,
      heat: true,
      cheese: true,
    },
    tags: {
      deal: true,
    },
    order: 5,
    toppings: [],
  },
  {
    name: 'Haram Deluxe',
    category: 'Pizza',
    description:
      'Authentische Zutaten, gewürzt mit orientalischen Aromen, machen die "Haram"-Pizza zu einem geschmackvollen Gaumenschmaus.',
    price: 14.9,
    image: 'assets/images/menu/items/Pizza-haram-deluxe.png',
    contains: {
      gluten: true,
      heat: true,
      pork: true,
      cheese: true,
    },
    tags: {},
    order: 6,
    toppings: [],
  },
  {
    name: 'Thelicious',
    category: 'Pizza',
    description:
      'Diese köstliche Pizza ist mit einer knusprigen Kruste, saftigen Tomaten, würzigem Mozzarella, frischem Basilikum und herzhafter Salami belegt, was zu einer perfekten Kombination von Aromen und Texturen führt, die jeden Bissen zu einem Geschmackserlebnis macht.',
    price: 13.9,
    image: 'assets/images/menu/items/Pizza-default.png',
    contains: {
      gluten: true,
      heat: true,
      cheese: true,
    },
    tags: {
      new: true,
    },
    order: 7,
    toppings: [],
  },
];

export const bowls: Array<Bowl> = [
  {
    name: 'Tikki spicy beef',
    category: 'Bowl',
    description:
      'Unsere "Rind"-Bowl vereint zartes Rindfleisch, knackiges Gemüse und aromatische Gewürze zu einer schmackhaften und nahrhaften Mahlzeit voller Genuss.',
    price: 15.9,
    image: 'assets/images/menu/items/Bowl-tikki-spicy-beef.png',
    contains: {
      beef: true,
      egg: true,
      cheese: true,
    },
    tags: { recommendation: true },
    order: 1,
    toppings: [],
  },
  {
    name: 'Shaka spicy Tuna',
    category: 'Bowl',
    description:
      'Unsere "Scharfer Thunfisch"-Bowl ist eine kraftvolle Kombination aus feurigem Thunfisch, frischem Gemüse und exotischen Gewürzen, die eine unvergessliche Geschmacksexplosion liefert.',
    price: 13.9,
    image: 'assets/images/menu/items/Bowl-shaka-spicy-tuna.png',
    contains: {
      fish: true,
      egg: true,
      cheese: true,
    },
    tags: {},
    order: 2,
    toppings: [],
  },
  {
    name: 'Aloha spicy shrimp',
    category: 'Bowl',
    description:
      'Unsere "Garnelen"-Bowl begeistert mit saftigen Garnelen, knusprigem Gemüse und einer verlockenden Mischung aus exotischen Gewürzen für einen unvergleichlichen Genussmoment.',
    price: 14.9,
    image: 'assets/images/menu/items/Bowl-aloha-spicy-shrimp.png',
    contains: {
      shrimp: true,
      egg: true,
      cheese: true,
    },
    tags: { deal: true },
    order: 3,
    toppings: [],
  },
  {
    name: 'BALI BEACH Bowl',
    category: 'Bowl',
    description:
      'Unsere "Garnelen"-Bowl begeistert mit saftigen Garnelen, knusprigem Gemüse und einer verlockenden Mischung aus exotischen Gewürzen für einen unvergleichlichen Genussmoment.',
    price: 14.9,
    image: 'assets/images/menu/items/Bowl-chicken.png',
    contains: {
      beef: true,
      egg: true,
      cheese: true,
    },
    tags: { new: true },
    order: 4,
    toppings: [],
  },
];

export const toppings: Topping[] = [
  {
    name: 'Salami',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Pizza-margherita.jpg',
    category: 'Pizza',
  },
  {
    name: 'Scharfe Salami',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Pizza-margherita.jpg',
    category: 'Pizza',
  },
  {
    name: 'Edammer',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Pizza-margherita.jpg',
    category: 'Pizza',
  },
  {
    name: 'Gouda',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Pizza-margherita.jpg',
    category: 'Pizza',
  },
  {
    name: 'Rucola',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Pizza-margherita.jpg',
    category: 'Pizza',
  },
  {
    name: 'Tomaten',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Pizza-margherita.jpg',
    category: 'Pizza',
  },
  {
    name: 'Oliven',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Pizza-margherita.jpg',
    category: 'Pizza',
  },
  {
    name: 'Schinken',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Pizza-margherita.jpg',
    category: 'Pizza',
  },
  {
    name: 'Thunfisch',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Pizza-margherita.jpg',
    category: 'Pizza',
  },
  {
    name: 'Ananas',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Pizza-margherita.jpg',
    category: 'Pizza',
  },
  {
    name: 'Spinat',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Pizza-margherita.jpg',
    category: 'Pizza',
  },
  {
    name: 'Pilze',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Pizza-margherita.jpg',
    category: 'Pizza',
  },
  {
    name: 'Mais',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Pizza-margherita.jpg',
    category: 'Pizza',
  },
  {
    name: 'Zwiebeln',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Pizza-margherita.jpg',
    category: 'Pizza',
  },
  {
    name: 'Tomatensauce',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Pizza-margherita.jpg',
    category: 'Pizza',
  },
  {
    name: 'BBQ-Sauce',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Pizza-margherita.jpg',
    category: 'Pizza',
  },
  {
    name: 'Hollondaise-Sauce',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Pizza-margherita.jpg',
    category: 'Pizza',
  },

  {
    name: 'Oliven',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Pizza-margherita.jpg',
    category: 'Bowl',
  },
  {
    name: 'Tomaten',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },
  {
    name: 'Edamame',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },
  {
    name: 'Soja-Sprossen',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },
  {
    name: 'Avocado',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },
  {
    name: 'Zwiebeln (rot)',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },
  {
    name: 'Garnelen',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },
  {
    name: 'Hühnchen',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },
  {
    name: 'Mango',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },

  {
    name: 'Lauchzwiebeln',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },
  {
    name: 'Karotten',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },
  {
    name: 'Basilikum',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },
  {
    name: 'Reis (Basmati)',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },
  {
    name: 'Rindfleisch (mariniert)',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },
  {
    name: 'Gurken',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },
  {
    name: 'Mais',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },
  {
    name: 'Paprika',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },
  {
    name: 'Thunfisch',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },
  {
    name: 'Schinken',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },
  {
    name: 'Ei',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },
  {
    name: 'Feta',
    description: 'Tomatensauce, Mozzarella, Basilikum',
    price: 5.5,
    image: 'assets/images/food/Bowl.jpg',
    category: 'Bowl',
  },
];
