import { Metadata } from 'next';
import { Analytics } from '@vercel/analytics/react';
import './global.css';

import Navbar from '../components/navbar';
import Footer from '../components/footer';
import Breadcrumb from '../components/breadcrumb';
import { TrpcProvider } from '../utils/trpc-provider';

export const metadata: Metadata = {
  title: 'Welcome to shop-poster',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Breadcrumb />
        <TrpcProvider>
        {children}
        </TrpcProvider>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
