import { Metadata } from 'next';
import './global.css';
import Navbar from './navbar';
import { Analytics } from '@vercel/analytics/react';

export const metadata: Metadata = {
  title: 'Welcome to shop-poster',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
